on:
  workflow_call:
    inputs:
      target-branch:
        required: false
        type: string
        default: main
      source-branch:
        required: false
        type: string
        default: development
      title:
        required: true
        type: string
      body-message:
        required: true
        type: string
      continue-on-error:
        required: false
        type: boolean
        default: true
    secrets:
      GITHUB_TOKEN:
        required: true

jobs:
  Create-pull-request:
    runs-on: ubuntu-latest

    - name: Create pull request
        run: gh pr create -B ${{ inputs.target-branch }} -H ${{ inputs.source-branch}} --title '${{ inputs.title}}' --body '${{ inputs.body-message}}' || ${{ inputs.continue-on-error }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}