on:
  workflow_call:
    inputs:
      working-directory:
        required: false
        type: string
        default: src
      execute-unit-tests:
        required: false
        type: string
        default: "true"
      name-test-script:
        required: false
        type: string
        default: test

jobs:
  Restore-dependencies-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Restore dependencies
        run: cd ${{ inputs.working-directory }} && npm install

      - name: Testing
        if: $ {{ inputs.execute-unit-tests == "true" }}
        run: |
          cd ${{ inputs.working-directory }} && npm run ${{ inputs.name-test-script }}
          
      - name: Zip Artifacts
        run: |
          zip -r ${{inputs.working-directory}}/node_modules.zip ${{inputs.working-directory}}/node_modules

      - name: Store node_modules
        uses: actions/upload-artifact@v3
        with:
          name: node_modules
          path: ${{inputs.working-directory}}/node_modules.zip
        

      

