on:
  workflow_call:
    inputs:
      working-directory:
        required: false
        type: string
        default: src
    secrets:
      NPM_TOKEN:
        required: true

jobs:
  Deploy-package-npm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Downloading node_modules
        uses: actions/download-artifact@v3
        with:
          name: node_modules

      - name: Unzip node_modules
        run: |
          unzip node_modules.zip
      
      - name: Check if node_modules exists
        run: |
          ls ${{ inputs.working-directory}}/node_modules

      - name: Generate lock file
        run: |
          cd ${{ inputs.working-directory}} && npm i --package-lock-only

      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - run: cd ${{ inputs.working-directory}} && npm ci
      - run: cd ${{ inputs.working-directory}} && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

        

      

