on:
  workflow_call:
    inputs:
      aws-region:
        required: false
        type: string
        default: "sa-east-1"
      stack-name:
        required: true
        type: string
      parameters-file-path:
        required: true
        type: string
      template-file:
        required: false
        type: string
        default: "template.yaml"
      api-gateway-name:
        required: true
        type: string
      stage-name:
        required: false
        type: string
        default: "dev"
    secrets:
      AWS_BUCKET_DEPLOY:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  
  Deploy-infra:
    uses: PePires58/ReusableWorkflows/.github/workflows/002_cloudformation_deploy_pipeline.yaml@main
    with: 
      aws-region: ${{ inputs.aws-region }}
      stack-name: ${{ inputs.stack-name }}
      parameters-file-path: ${{ inputs.parameters-file-path }}
      template-file: ${{ inputs.template-file }}
    secrets:
      AWS_BUCKET_DEPLOY: ${{ secrets.AWS_BUCKET_DEPLOY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  Deploy-stage:
    needs: [Deploy-infra]
    uses: PePires58/ReusableWorkflows/.github/workflows/004_apigateway_deploy_stage.yaml@main
    with: 
      api-gateway-name: ${{ inputs.api-gateway-name }}
      stage-name: ${{ inputs.stage-name }}
      aws-region: ${{ inputs.aws-region }}
    secrets:
      AWS_BUCKET_DEPLOY: ${{ secrets.AWS_BUCKET_DEPLOY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}