on:
  workflow_call:
    inputs:
      working-directory:
        required: false
        type: string
        default: src
      execute-unit-tests:
        required: false
        type: string
        default: "true"
      aws-region:
        required: false
        type: string
        default: "sa-east-1"
      stack-name:
        required: true
        type: string
      parameters-file-path:
        required: true
        type: string
      template-file:
        required: false
        type: string
        default: "template.yaml"
    secrets:
      AWS_BUCKET_DEPLOY:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  
  Build-test-dotnet:
    uses: PePires58/ReusableWorkflows/.github/workflows/006_dotnet_build.yaml@main
    with:
      working-directory: ${{ inputs.working-directory }}
      execute-unit-tests: ${{ inputs.execute-unit-tests }}

  Deploy-dotnet-api:
    needs: [Build-test-dotnet]
    uses: PePires58/ReusableWorkflows/.github/workflows/006_dotnet_deploy.yaml@main
    with: 
      aws-region : ${{ inputs.aws-region }}
      stack-name: ${{ inputs.stack-name }}
      parameters-file-path: ${{ inputs.parameters-file-path }}
      template-file: ${{ inputs.template-file }}
      working-directory: ${{ inputs.working-directory }}
    secrets:
      AWS_BUCKET_DEPLOY: ${{ secrets.AWS_BUCKET_DEPLOY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}